<?php 
$users = $viewData['users'];
Echo "Estas en Select.pthml";
// echo "<pre>Users";    
//     print_r($users);
// echo "</pre>";


?>
<h1 class="page-header">Users</h1>

<a href="/crud/insert">Insert</a>
<div class="table-responsive">
<table class="table table-striped">
    <?php foreach($users as $id => $user):?>
        <tr>
           <?php 
            //$user = explode(",", $user);
            foreach ($user as $iduser => $value):
                
            ?>               
                <td><?php echo $value;?></td>
            <?php endforeach; ?>
            <td>
                <a href="/crud/update/iduser/<?=$user['iduser'];?>">Update</a> | 
                <a href="/crud/delete/iduser/<?=$user['iduser'];?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
</div>